# Generated by Django 4.2.3 on 2023-07-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='short_description',
            field=models.CharField(default='ovos e uma caixa de cereal.', max_length=100),
        ),
        migrations.AddField(
            model_name='categoria',
            name='value',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
