# Generated by Django 4.2.3 on 2023-07-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_categoria_short_description_categoria_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='short_description',
            field=models.CharField(max_length=100),
        ),
    ]
