# Generated by Django 4.2.3 on 2023-07-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_category_transaction_delete_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transacao',
        ),
    ]
