# Generated by Django 4.2.3 on 2023-07-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_rename_category_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='dt_criation',
        ),
        migrations.AddField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
