# Generated by Django 4.2.3 on 2023-07-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0010_alter_transacao_dt_criation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='dt_criation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='dt_criation',
            field=models.DateTimeField(),
        ),
    ]
