# Generated by Django 4.2.3 on 2023-07-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0012_alter_categoria_dt_criation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criation', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('money', models.CharField(max_length=100)),
            ],
        ),
    ]
