# Generated by Django 4.2.3 on 2023-07-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0013_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
