# Generated by Django 4.2.3 on 2023-07-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0014_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='dt_criation',
            new_name='dt_creation',
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='dt_criation',
            new_name='dt_creation',
        ),
    ]
